name: singularity
version: 1.1.3+5
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.19.1 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  google_fonts: ^2.3.1
  url_launcher: ^6.0.20
  screenshot: ^1.2.3
  share_plus: ^4.0.4
  path_provider: ^2.0.9
  upgrader: ^6.2.0
  firebase_core: ^2.8.0
  cloud_firestore: ^4.4.5
  build_runner: ^2.3.3
  json_annotation: ^4.8.0
  json_serializable: ^6.6.1
  flutter_svg: ^2.0.4
  firebase_auth: ^4.3.0
  google_sign_in: ^6.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^1.0.0
  flutter_native_splash: ^2.1.5
  flutter_test: 
    sdk: flutter

flutter_native_splash: 
  color: '#000000'
  image: assets/app_icon.png

flutter: 
  assets: 
    - assets/
  uses-material-design: true

