  List<String> topics = [
    "Mercury",
    "Venus",
    "Earth",
    "Mars",
    "Jupiter",
    "Saturn",
    "Uranus",
    "Neptune",
    "Pluto",
    'Galaxy',
    'Black hole',
    'Star',
    'Nebula',
    'Supernova',
    'Planet',
    'Asteroid',
    'Comet',
    'Solar system',
    'Gravity',
    'Universe',
    'Dark matter',
    'Dark energy',
    'Spacecraft',
    'Rocket',
    'Telescope',
    'Extraterrestrial',
    'Cosmic radiation',
    'Orbital',
    'Interstellar',
    'Milky Way',
    'Constellation',
    'Lunar',
    'Martian',
    'Exoplanet',
    'Red giant',
    'White dwarf',
    'Cosmic dust',
    'Lunar eclipse',
    'Solar eclipse',
    'Asteroid belt',
    'Kuiper belt',
    'Meteorite',
    'Intergalactic',
    'Event horizon',
    'Gravitational waves',
    'Big bang',
    'Wormhole',
    'Singularity',
    'Time dilation',
    'Blackbody radiation',
    'Magnetosphere',
    'Star cluster',
    'Hubble telescope',
    'Neutron star',
    'Pulsar',
    'Cosmic ray',
    'Planetary system'
  ];